-- MySQL Script generated by MySQL Workbench
-- Sat Apr 26 18:22:30 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bd-gestion-tickets
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd-gestion-tickets
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd-gestion-tickets` DEFAULT CHARACTER SET utf8 ;
USE `bd-gestion-tickets` ;

-- -----------------------------------------------------
-- Table `bd-gestion-tickets`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-gestion-tickets`.`categoria` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `nombre_categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcategoria`),
  UNIQUE INDEX `nombre_categoria` (`nombre_categoria` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bd-gestion-tickets`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-gestion-tickets`.`estado` (
  `idestado` INT NOT NULL AUTO_INCREMENT,
  `nombre_estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idestado`),
  UNIQUE INDEX `nombre_estado` (`nombre_estado` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bd-gestion-tickets`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-gestion-tickets`.`persona` (
  `idpersona` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `dni` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`idpersona`),
  UNIQUE INDEX `dni` (`dni` ASC) VISIBLE,
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bd-gestion-tickets`.`prioridad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-gestion-tickets`.`prioridad` (
  `idprioridad` INT NOT NULL AUTO_INCREMENT,
  `nombre_prioridad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idprioridad`),
  UNIQUE INDEX `nombre_prioridad` (`nombre_prioridad` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bd-gestion-tickets`.`tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-gestion-tickets`.`tipo` (
  `idtipo` INT NOT NULL AUTO_INCREMENT,
  `nombre_tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtipo`),
  UNIQUE INDEX `nombre_tipo` (`nombre_tipo` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bd-gestion-tickets`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-gestion-tickets`.`rol` (
  `idrol` INT NOT NULL AUTO_INCREMENT,
  `nombre_rol` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idrol`),
  UNIQUE INDEX `nombre_rol` (`nombre_rol` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bd-gestion-tickets`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-gestion-tickets`.`usuario` (
  `idpersona` INT NOT NULL,
  `nombre_usuario` VARCHAR(45) NOT NULL,
  `contrasenia` VARCHAR(45) NOT NULL,
  `idrol` INT NOT NULL,
  PRIMARY KEY (`idpersona`),
  UNIQUE INDEX `nombre_usuario` (`nombre_usuario` ASC) VISIBLE,
  INDEX `fk_usuario_rol1_idx` (`idrol` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_persona`
    FOREIGN KEY (`idpersona`)
    REFERENCES `bd-gestion-tickets`.`persona` (`idpersona`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_usuario_rol1`
    FOREIGN KEY (`idrol`)
    REFERENCES `bd-gestion-tickets`.`rol` (`idrol`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bd-gestion-tickets`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-gestion-tickets`.`ticket` (
  `idticket` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  `fecha_creacion` DATE NOT NULL,
  `fecha_mod_est` DATE NULL DEFAULT NULL,
  `idpersona` INT NOT NULL,
  `idestado` INT NOT NULL,
  `idtipo` INT NOT NULL,
  `idprioridad` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idticket`),
  -- UNIQUE INDEX `idpersona` (`idpersona` ASC) VISIBLE,
  INDEX `fk_ticket_usuario1_idx` (`idpersona` ASC) VISIBLE,
  INDEX `fk_ticket_estado1_idx` (`idestado` ASC) VISIBLE,
  INDEX `fk_ticket_tipo1_idx` (`idtipo` ASC) VISIBLE,
  INDEX `fk_ticket_prioridad1_idx` (`idprioridad` ASC) VISIBLE,
  CONSTRAINT `fk_ticket_estado1`
    FOREIGN KEY (`idestado`)
    REFERENCES `bd-gestion-tickets`.`estado` (`idestado`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ticket_prioridad1`
    FOREIGN KEY (`idprioridad`)
    REFERENCES `bd-gestion-tickets`.`prioridad` (`idprioridad`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ticket_tipo1`
    FOREIGN KEY (`idtipo`)
    REFERENCES `bd-gestion-tickets`.`tipo` (`idtipo`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ticket_usuario1`
    FOREIGN KEY (`idpersona`)
    REFERENCES `bd-gestion-tickets`.`usuario` (`idpersona`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bd-gestion-tickets`.`respuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-gestion-tickets`.`respuesta` (
  `idrespuesta` INT NOT NULL AUTO_INCREMENT,
  `contenido` TEXT NOT NULL,
  `fecha_respuesta` DATE NOT NULL,
  `idticket` INT NOT NULL,
  `idautor` INT NOT NULL,
  PRIMARY KEY (`idrespuesta`),
  UNIQUE INDEX `idticket` (`idticket` ASC) VISIBLE,
  INDEX `fk_respuesta_ticket1_idx` (`idticket` ASC) VISIBLE,
  INDEX `fk_respuesta_usuario1_idx` (`idautor` ASC) VISIBLE,
  CONSTRAINT `fk_respuesta_ticket1`
    FOREIGN KEY (`idticket`)
    REFERENCES `bd-gestion-tickets`.`ticket` (`idticket`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_respuesta_usuario1`
    FOREIGN KEY (`idautor`)
    REFERENCES `bd-gestion-tickets`.`usuario` (`idpersona`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bd-gestion-tickets`.`ticket_has_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-gestion-tickets`.`ticket_has_categoria` (
  `idticket` INT NOT NULL,
  `idcategoria` INT NOT NULL,
  PRIMARY KEY (`idticket`, `idcategoria`),
  INDEX `fk_ticket_has_categoria_categoria1_idx` (`idcategoria` ASC) VISIBLE,
  INDEX `fk_ticket_has_categoria_ticket1_idx` (`idticket` ASC) VISIBLE,
  CONSTRAINT `fk_ticket_has_categoria_categoria1`
    FOREIGN KEY (`idcategoria`)
    REFERENCES `bd-gestion-tickets`.`categoria` (`idcategoria`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ticket_has_categoria_ticket1`
    FOREIGN KEY (`idticket`)
    REFERENCES `bd-gestion-tickets`.`ticket` (`idticket`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Se setean los valores bases
-- -----------------------------------------------------

INSERT INTO `bd-gestion-tickets`.`estado` (`idestado`, `nombre_estado`) VALUES ('1', 'Cerrado');
INSERT INTO `bd-gestion-tickets`.`estado` (`idestado`, `nombre_estado`) VALUES ('2', 'Abierto');
INSERT INTO `bd-gestion-tickets`.`prioridad` (`idprioridad`, `nombre_prioridad`) VALUES ('1', 'Alta');
INSERT INTO `bd-gestion-tickets`.`prioridad` (`idprioridad`, `nombre_prioridad`) VALUES ('2', 'Media');
INSERT INTO `bd-gestion-tickets`.`prioridad` (`idprioridad`, `nombre_prioridad`) VALUES ('3', 'Baja');
INSERT INTO `bd-gestion-tickets`.`rol` (`idrol`, `nombre_rol`) VALUES ('1', 'Cliente');
INSERT INTO `bd-gestion-tickets`.`rol` (`idrol`, `nombre_rol`) VALUES ('2', 'Empleado');
INSERT INTO `bd-gestion-tickets`.`rol` (`idrol`, `nombre_rol`) VALUES ('3', 'Administrador');
INSERT INTO `bd-gestion-tickets`.`tipo` (`idtipo`, `nombre_tipo`) VALUES ('1', 'Consulta');
INSERT INTO `bd-gestion-tickets`.`tipo` (`idtipo`, `nombre_tipo`) VALUES ('2', 'Reclamo');
INSERT INTO `bd-gestion-tickets`.`tipo` (`idtipo`, `nombre_tipo`) VALUES ('3', 'Notificacion');
INSERT INTO `bd-gestion-tickets`.`categoria` (`idcategoria`, `nombre_categoria`) VALUES ('1', 'A1');
INSERT INTO `bd-gestion-tickets`.`categoria` (`idcategoria`, `nombre_categoria`) VALUES ('2', 'A2');
INSERT INTO `bd-gestion-tickets`.`categoria` (`idcategoria`, `nombre_categoria`) VALUES ('3', 'A3');
INSERT INTO `bd-gestion-tickets`.`persona` (`idpersona`, `nombre`, `apellido`, `dni`, `email`, `telefono`) VALUES ('1', 'Pepito', 'Pruebita', '11111111', 'pepoprueba@hotmail.com', '1111111111');
INSERT INTO `bd-gestion-tickets`.`persona` (`idpersona`, `nombre`, `apellido`, `dni`, `email`, `telefono`) VALUES ('2', 'Admin', 'Administra', '22222222', 'adminemail@hotmail.com', '2222222222');
INSERT INTO `bd-gestion-tickets`.`usuario` (`idpersona`, `nombre_usuario`, `contrasenia`, `idrol`) VALUES ('1', 'PepeCliente22', 'contraseña', '1');
INSERT INTO `bd-gestion-tickets`.`usuario` (`idpersona`, `nombre_usuario`, `contrasenia`, `idrol`) VALUES ('2', 'AdminGod', 'administra23', '3');
INSERT INTO `bd-gestion-tickets`.`ticket` (`idticket`, `titulo`, `descripcion`, `fecha_creacion`, `fecha_mod_est`, `idpersona`, `idestado`, `idtipo`, `idprioridad`) VALUES ('1', 'TituloTicket', 'Descripcion', '2020-06-20', '2020-06-20', '2', '1', '1', '1');
INSERT INTO `bd-gestion-tickets`.`ticket_has_categoria` (`idticket`, `idcategoria`) VALUES ('1', '1');
INSERT INTO `bd-gestion-tickets`.`respuesta` (`idrespuesta`, `contenido`, `fecha_respuesta`, `idticket`, `idautor`) VALUES ('1', 'Respuesta', '2020-06-20', '1', '2');

