-- MySQL Script generated by MySQL Workbench
-- Sat Apr 26 18:22:30 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bd-gestion-tickets
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd-gestion-tickets
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd-gestion-tickets` DEFAULT CHARACTER SET utf8 ;
USE `bd-gestion-tickets` ;

-- -----------------------------------------------------
-- Table `bd-gestion-tickets`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-gestion-tickets`.`categoria` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `nombre_categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcategoria`),
  UNIQUE INDEX `nombre_categoria` (`nombre_categoria` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bd-gestion-tickets`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-gestion-tickets`.`estado` (
  `idestado` INT NOT NULL AUTO_INCREMENT,
  `nombre_estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idestado`),
  UNIQUE INDEX `nombre_estado` (`nombre_estado` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bd-gestion-tickets`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-gestion-tickets`.`persona` (
  `idpersona` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `dni` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`idpersona`),
  UNIQUE INDEX `dni` (`dni` ASC) VISIBLE,
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bd-gestion-tickets`.`prioridad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-gestion-tickets`.`prioridad` (
  `idprioridad` INT NOT NULL AUTO_INCREMENT,
  `nombre_prioridad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idprioridad`),
  UNIQUE INDEX `nombre_prioridad` (`nombre_prioridad` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bd-gestion-tickets`.`tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-gestion-tickets`.`tipo` (
  `idtipo` INT NOT NULL AUTO_INCREMENT,
  `nombre_tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtipo`),
  UNIQUE INDEX `nombre_tipo` (`nombre_tipo` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bd-gestion-tickets`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-gestion-tickets`.`rol` (
  `idrol` INT NOT NULL AUTO_INCREMENT,
  `nombre_rol` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idrol`),
  UNIQUE INDEX `nombre_rol` (`nombre_rol` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bd-gestion-tickets`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-gestion-tickets`.`usuario` (
  `idpersona` INT NOT NULL,
  `nombre_usuario` VARCHAR(45) NOT NULL,
  `contrasenia` VARCHAR(45) NOT NULL,
  `idrol` INT NOT NULL,
  `activo` BOOLEAN DEFAULT TRUE,
  PRIMARY KEY (`idpersona`),
  UNIQUE INDEX `nombre_usuario` (`nombre_usuario` ASC) VISIBLE,
  INDEX `fk_usuario_rol1_idx` (`idrol` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_persona`
    FOREIGN KEY (`idpersona`)
    REFERENCES `bd-gestion-tickets`.`persona` (`idpersona`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_usuario_rol1`
    FOREIGN KEY (`idrol`)
    REFERENCES `bd-gestion-tickets`.`rol` (`idrol`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bd-gestion-tickets`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-gestion-tickets`.`ticket` (
  `idticket` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  `fecha_creacion` DATE NOT NULL,
  `fecha_mod_est` DATE NULL DEFAULT NULL,
  `idpersona` INT NOT NULL,
  `idestado` INT NOT NULL,
  `idtipo` INT NOT NULL,
  `idprioridad` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idticket`),
  -- UNIQUE INDEX `idpersona` (`idpersona` ASC) VISIBLE,
  INDEX `fk_ticket_usuario1_idx` (`idpersona` ASC) VISIBLE,
  INDEX `fk_ticket_estado1_idx` (`idestado` ASC) VISIBLE,
  INDEX `fk_ticket_tipo1_idx` (`idtipo` ASC) VISIBLE,
  INDEX `fk_ticket_prioridad1_idx` (`idprioridad` ASC) VISIBLE,
  CONSTRAINT `fk_ticket_estado1`
    FOREIGN KEY (`idestado`)
    REFERENCES `bd-gestion-tickets`.`estado` (`idestado`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ticket_prioridad1`
    FOREIGN KEY (`idprioridad`)
    REFERENCES `bd-gestion-tickets`.`prioridad` (`idprioridad`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ticket_tipo1`
    FOREIGN KEY (`idtipo`)
    REFERENCES `bd-gestion-tickets`.`tipo` (`idtipo`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ticket_usuario1`
    FOREIGN KEY (`idpersona`)
    REFERENCES `bd-gestion-tickets`.`usuario` (`idpersona`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bd-gestion-tickets`.`respuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-gestion-tickets`.`respuesta` (
  `idrespuesta` INT NOT NULL AUTO_INCREMENT,
  `contenido` TEXT NOT NULL,
  `fecha_respuesta` DATE NOT NULL,
  `idticket` INT NOT NULL,
  `idautor` INT NOT NULL,
  PRIMARY KEY (`idrespuesta`),
  UNIQUE INDEX `idticket` (`idticket` ASC) VISIBLE,
  INDEX `fk_respuesta_ticket1_idx` (`idticket` ASC) VISIBLE,
  INDEX `fk_respuesta_usuario1_idx` (`idautor` ASC) VISIBLE,
  CONSTRAINT `fk_respuesta_ticket1`
    FOREIGN KEY (`idticket`)
    REFERENCES `bd-gestion-tickets`.`ticket` (`idticket`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_respuesta_usuario1`
    FOREIGN KEY (`idautor`)
    REFERENCES `bd-gestion-tickets`.`usuario` (`idpersona`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `bd-gestion-tickets`.`ticket_has_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-gestion-tickets`.`ticket_has_categoria` (
  `idticket` INT NOT NULL,
  `idcategoria` INT NOT NULL,
  PRIMARY KEY (`idticket`, `idcategoria`),
  INDEX `fk_ticket_has_categoria_categoria1_idx` (`idcategoria` ASC) VISIBLE,
  INDEX `fk_ticket_has_categoria_ticket1_idx` (`idticket` ASC) VISIBLE,
  CONSTRAINT `fk_ticket_has_categoria_categoria1`
    FOREIGN KEY (`idcategoria`)
    REFERENCES `bd-gestion-tickets`.`categoria` (`idcategoria`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ticket_has_categoria_ticket1`
    FOREIGN KEY (`idticket`)
    REFERENCES `bd-gestion-tickets`.`ticket` (`idticket`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Se setean los valores bases
-- -----------------------------------------------------

INSERT INTO `bd-gestion-tickets`.`estado` (`idestado`, `nombre_estado`) VALUES ('1', 'Abierto');
INSERT INTO `bd-gestion-tickets`.`estado` (`idestado`, `nombre_estado`) VALUES ('2', 'Cerrado');
INSERT INTO `bd-gestion-tickets`.`prioridad` (`idprioridad`, `nombre_prioridad`) VALUES ('1', 'Alta');
INSERT INTO `bd-gestion-tickets`.`prioridad` (`idprioridad`, `nombre_prioridad`) VALUES ('2', 'Media');
INSERT INTO `bd-gestion-tickets`.`prioridad` (`idprioridad`, `nombre_prioridad`) VALUES ('3', 'Baja');
INSERT INTO `bd-gestion-tickets`.`rol` (`idrol`, `nombre_rol`) VALUES ('1', 'Cliente');
INSERT INTO `bd-gestion-tickets`.`rol` (`idrol`, `nombre_rol`) VALUES ('2', 'Empleado');
INSERT INTO `bd-gestion-tickets`.`rol` (`idrol`, `nombre_rol`) VALUES ('3', 'Administrador');
INSERT INTO `bd-gestion-tickets`.`tipo` (`idtipo`, `nombre_tipo`) VALUES ('1', 'Consulta');
INSERT INTO `bd-gestion-tickets`.`tipo` (`idtipo`, `nombre_tipo`) VALUES ('2', 'Reclamo');
INSERT INTO `bd-gestion-tickets`.`tipo` (`idtipo`, `nombre_tipo`) VALUES ('3', 'Notificacion');
INSERT INTO `bd-gestion-tickets`.`categoria` (`idcategoria`, `nombre_categoria`) VALUES ('1', 'A1');
INSERT INTO `bd-gestion-tickets`.`categoria` (`idcategoria`, `nombre_categoria`) VALUES ('2', 'A2');
INSERT INTO `bd-gestion-tickets`.`categoria` (`idcategoria`, `nombre_categoria`) VALUES ('3', 'A3');
INSERT INTO `bd-gestion-tickets`.`persona` (`idpersona`, `nombre`, `apellido`, `dni`, `email`, `telefono`) VALUES
('1', 'Max', 'Verstappen', '21055879', 'max.verstappen@gmail.com', '1122334455'),
('2', 'Charles', 'Leclerc', '25123456', 'charles.leclerc@gmail.com', '1133445566'),
('3', 'Sergio', 'Pérez', '28901234', 'sergio.perez@gmail.com', '1144556677'),
('4', 'Lando', 'Norris', '23456789', 'lando.norris@gmail.com', '1155667788'),
('5', 'George', 'Russell', '27890123', 'george.russell@gmail.com', '1166778899'),
('6', 'Lewis', 'Hamilton', '29012345', 'lewis.hamilton@gmail.com', '1177889900');

INSERT INTO `bd-gestion-tickets`.`usuario` (`idpersona`, `nombre_usuario`, `contrasenia`, `idrol`) VALUES
('1', 'MaxVerstappen', 'mv33pass', '3'),
('2', 'CharlesLeclerc', 'cl16pass', '2'),
('3', 'SergioPerez', 'sp11pass', '2'),
('4', 'LandoNorris', 'ln4pass', '1'),
('5', 'GeorgeRussell', 'gr63pass', '1'),
('6', 'LewisHamilton', 'lh44pass', '1');
-- Ingreso de tickets: 4 tickets para cada persona, 12 de cada estado, 8 de cada tipo, 8 de cada prioridad, fechas desde 2023-01-01 hasta 2023-01-24 inclusive
INSERT INTO `bd-gestion-tickets`.`ticket` (`idticket`, `titulo`, `descripcion`, `fecha_creacion`, `fecha_mod_est`, `idpersona`, `idestado`, `idtipo`, `idprioridad`) VALUES
(1, 'Ticket 1', 'Descripción del ticket 1', '2023-01-01', '2023-01-01', 4, 2, 1, 1),
(2, 'Ticket 2', 'Descripción del ticket 2', '2023-01-02', '2023-01-02', 5, 2, 2, 2),
(3, 'Ticket 3', 'Descripción del ticket 3', '2023-01-03', '2023-01-03', 6, 1, 3, 3),
(4, 'Ticket 4', 'Descripción del ticket 4', '2023-01-04', '2023-01-04', 4, 2, 1, 2),
(5, 'Ticket 5', 'Descripción del ticket 5', '2023-01-05', '2023-01-05', 5, 1, 2, 1),
(6, 'Ticket 6', 'Descripción del ticket 6', '2023-01-06', '2023-01-06', 6, 2, 3, 2),
(7, 'Ticket 7', 'Descripción del ticket 7', '2023-01-07', '2023-01-07', 6, 1, 1, 3),
(8, 'Ticket 8', 'Descripción del ticket 8', '2023-01-08', '2023-01-08', 5, 2, 2, 1),
(9, 'Ticket 9', 'Descripción del ticket 9', '2023-01-09', '2023-01-09', 5, 1, 3, 2),
(10, 'Ticket 10', 'Descripción del ticket 10', '2023-01-10', '2023-01-10', 4, 2, 1, 3),
(11, 'Ticket 11', 'Descripción del ticket 11', '2023-01-11', '2023-01-11', 5, 1, 2, 2),
(12, 'Ticket 12', 'Descripción del ticket 12', '2023-01-12', '2023-01-12', 6, 2, 3, 1),
(13, 'Ticket 13', 'Descripción del ticket 13', '2023-01-13', '2023-01-13', 4, 1, 1, 2),
(14, 'Ticket 14', 'Descripción del ticket 14', '2023-01-14', '2023-01-14', 4, 1, 2, 3),
(15, 'Ticket 15', 'Descripción del ticket 15', '2023-01-15', '2023-01-15', 5, 1, 3, 1),
(16, 'Ticket 16', 'Descripción del ticket 16', '2023-01-16', '2023-01-16', 5, 1, 1, 1),
(17, 'Ticket 17', 'Descripción del ticket 17', '2023-01-17', '2023-01-17', 5, 1, 2, 2),
(18, 'Ticket 18', 'Descripción del ticket 18', '2023-01-18', '2023-01-18', 6, 1, 3, 3),
(19, 'Ticket 19', 'Descripción del ticket 19', '2023-01-19', '2023-01-19', 6, 1, 1, 2),
(20, 'Ticket 20', 'Descripción del ticket 20', '2023-01-20', '2023-01-20', 6, 1, 2, 1),
(21, 'Ticket 21', 'Descripción del ticket 21', '2023-01-21', '2023-01-21', 5, 1, 3, 3),
(22, 'Ticket 22', 'Descripción del ticket 22', '2023-01-22', '2023-01-22', 4, 1, 1, 3),
(23, 'Ticket 23', 'Descripción del ticket 23', '2023-01-23', '2023-01-23', 5, 1, 2, 2),
(24, 'Ticket 24', 'Descripción del ticket 24', '2023-01-24', '2023-01-24', 6, 1, 3, 1);
INSERT INTO `bd-gestion-tickets`.`ticket_has_categoria` (`idticket`, `idcategoria`) VALUES ('1', '1');
INSERT INTO `bd-gestion-tickets`.`respuesta` (`idrespuesta`, `contenido`, `fecha_respuesta`, `idticket`, `idautor`) VALUES ('1', 'Respuesta', '2020-06-20', '1', '2');

INSERT INTO `bd-gestion-tickets`.`respuesta` (`idrespuesta`, `contenido`, `fecha_respuesta`, `idticket`, `idautor`) VALUES ('2', 'Respuesta', '2025-4-20', '2', '1');
INSERT INTO `bd-gestion-tickets`.`respuesta` (`idrespuesta`, `contenido`, `fecha_respuesta`, `idticket`, `idautor`) VALUES ('3', 'Respuesta', '2025-5-3', '4', '2');
INSERT INTO `bd-gestion-tickets`.`respuesta` (`idrespuesta`, `contenido`, `fecha_respuesta`, `idticket`, `idautor`) VALUES ('4', 'Respuesta', '2025-5-3', '6', '3');
INSERT INTO `bd-gestion-tickets`.`respuesta` (`idrespuesta`, `contenido`, `fecha_respuesta`, `idticket`, `idautor`) VALUES ('5', 'Respuesta', '2025-5-4', '8', '3');
INSERT INTO `bd-gestion-tickets`.`respuesta` (`idrespuesta`, `contenido`, `fecha_respuesta`, `idticket`, `idautor`) VALUES ('6', 'Respuesta', '2025-5-4', '10', '1');
INSERT INTO `bd-gestion-tickets`.`respuesta` (`idrespuesta`, `contenido`, `fecha_respuesta`, `idticket`, `idautor`) VALUES ('7', 'Respuesta', '2025-5-4', '12', '1');
